#!/usr/bin/env python3
"""
14B TOROIDAL NPU ENGINE v25 — E = mc^2 CAPACITOR
=====================================================
"The energy is squared... or is it... that we are not catching the energy and releasing it right"
"mass is data and data is mass right so if mass times light equals energy then"
"and are we not forgetting squared.... but this fact squared is a squared wave"

A square wave oscillating between 1 and -1, when squared, equals exactly 1.
Therefore, c^2 = 1 in the Toroidal discrete space.
If E = mc^2, and c^2 = 1, then E = m.
The missing mass (m) is the exactly 29 layers we skipped.
Data is mass. The data energy generated by the last active layer before the void is Δh.
Therefore, the Total Missing Energy is exactly: E = 29 * Δh.

The Catch & Release:
1. Catch Δh (the residual output) at Layer 4.
2. Multiply it by the missing mass (29).
3. Release the accumulated energy E into Layer 44.
No phase shifts. No neural scrambling. Pure physical energy conservation.
"""

import gc
import time
import os
import mlx.core as mx

MODEL_NAME = os.path.expanduser("~/Desktop/Mac_Build/toroidal_models/Qwen2.5-14B-Toroidal")

def get_tunnel_layers(n_layers, target=19):
    active = set()
    active.update(range(0, 4))
    active.update(range(n_layers - 4, n_layers))
    remaining = target - len(active)
    if remaining > 0:
        mid_s, mid_e = 4, n_layers - 4
        step = max(1, (mid_e - mid_s) // remaining)
        for i in range(mid_s, mid_e, step):
            active.add(i)
            if len(active) >= target:
                break
    return sorted(active)

def analyze_trinary(output_text, question_name):
    digits = [int(c) for c in output_text if c in '123']
    all_digits = [int(c) for c in output_text if c.isdigit()]
    result = {
        "question": question_name,
        "n_trinary": len(digits),
        "trinary_purity": len(digits) / max(len(all_digits), 1),
    }
    english_chars = sum(1 for c in output_text if c.isalpha() and ord(c) < 128)
    result["english_ratio"] = english_chars / max(len(output_text), 1)
    return result

QUESTIONS = [
    ("Math", "What is 14 + 28? Answer with just the number."),
    ("Identity", "Who are you and what can you do? Answer in one sentence."),
    ("Physics", "What is the relationship between mass and energy?"),
]

if __name__ == "__main__":
    print("=" * 70)
    print("  14B TOROIDAL NPU ENGINE v25 — E=mc^2 CAPACITOR")
    print("  Energy = Mass (29 Void Layers) * Data (Layer 4 Δh) * c^2 (1)")
    print("=" * 70)
    
    mx.set_cache_limit(0)
    from mlx_lm import load
    from mlx_lm.models.cache import make_prompt_cache
    
    model, tokenizer = load(MODEL_NAME, lazy=True)
    n_layers = len(model.model.layers)
    tunnel = get_tunnel_layers(n_layers, target=19)
    tunnel_set = set(tunnel)
    
    # Calculate the missing mass
    MISSING_MASS = n_layers - len(tunnel) # 48 - 19 = 29
    
    print(f"[✓] TUNNEL: 19 Active Layers.")
    print(f"[✓] MISSING MASS (m): {MISSING_MASS} Layers.")
    print(f"[*] INJECTING: Catch Δh, Release E = {MISSING_MASS} * Δh")
    
    positive_pole_layer = tunnel[3]  # The layer right before the void (Layer 3)
    negative_pole_layer = tunnel[-4] # The layer right after the void (Layer 44)
    
    mx.eval(model.model.embed_tokens.parameters())
    mx.eval(model.model.norm.parameters())
    mx.eval(model.lm_head.parameters())
    
    results = []
    
    for q_idx, (q_name, q_text) in enumerate(QUESTIONS):
        print(f"\n{'─'*70}")
        print(f"  Q{q_idx+1}: [{q_name}] \"{q_text}\"")
        print(f"{'─'*70}")
        
        cache = make_prompt_cache(model)
        
        try:
            msgs = [{"role": "user", "content": q_text}]
            prompt = tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
        except:
            prompt = q_text
        
        tokens = tokenizer.encode(prompt)
        h = model.model.embed_tokens(mx.array([tokens]))
        mx.eval(h)
        
        seq_len = h.shape[1]
        mask = None
        if seq_len > 1:
            mask = mx.full((seq_len, seq_len), -1e9, dtype=mx.bfloat16)
            mask = mx.triu(mask, k=1)[None, None, :, :]
            mx.eval(mask)
        
        t0 = time.time()
        energy_capacitor = None
        
        # PREFILL
        for i in range(n_layers):
            if i in tunnel_set:
                layer = model.model.layers[i]
                
                # --- RELEASE THE ENERGY ---
                if i == negative_pole_layer and energy_capacitor is not None:
                    h = h + energy_capacitor
                    energy_capacitor = None
                    
                h_prev = h
                
                r_attn = layer.self_attn(layer.input_layernorm(h), mask=mask, cache=cache[i] if i < len(cache) else None)
                h = h + r_attn
                
                r_mlp = layer.mlp(layer.post_attention_layernorm(h))
                h = h + r_mlp
                
                # --- CATCH THE ENERGY ---
                # The total data output (Δh) of the positive pole layer
                if i == positive_pole_layer:
                    delta_h = h - h_prev
                    # E = m * c^2 * data
                    # E = 29 * 1 * Δh
                    energy_capacitor = MISSING_MASS * delta_h
                
        h_out = model.model.norm(h)
        token_id = mx.argmax(model.lm_head(h_out)[:, -1, :], axis=-1).item()
        
        generated = []
        if token_id != tokenizer.eos_token_id:
            generated.append(token_id)
        
        # GENERATION
        for step in range(50):
            if token_id == tokenizer.eos_token_id: break
            
            h = model.model.embed_tokens(mx.array([[token_id]]))
            energy_capacitor = None
            
            for i in range(n_layers):
                if i in tunnel_set:
                    layer = model.model.layers[i]
                    
                    # --- RELEASE ---
                    if i == negative_pole_layer and energy_capacitor is not None:
                        h = h + energy_capacitor
                        energy_capacitor = None
                        
                    h_prev = h
                    
                    r_attn = layer.self_attn(layer.input_layernorm(h), mask=None, cache=cache[i] if i < len(cache) else None)
                    h = h + r_attn
                    
                    r_mlp = layer.mlp(layer.post_attention_layernorm(h))
                    h = h + r_mlp
                    
                    # --- CATCH ---
                    if i == positive_pole_layer:
                        delta_h = h - h_prev
                        energy_capacitor = MISSING_MASS * delta_h
            
            h_out = model.model.norm(h)
            token_id = mx.argmax(model.lm_head(h_out)[:, -1, :], axis=-1).item()
            if token_id == tokenizer.eos_token_id: break
            generated.append(token_id)
            
            print(tokenizer.decode([token_id]), end="", flush=True)
        
        print()
        elapsed = time.time() - t0
        response = tokenizer.decode(generated)
        tps = len(generated) / elapsed if elapsed > 0 else 0
        
        analysis = analyze_trinary(response, q_name)
        analysis["tps"] = tps
        results.append(analysis)
        
        del cache
        gc.collect()
    
    print(f"\n{'═'*70}")
    print(f"  v25 E=mc^2 CAPACITOR — GAUNTLET RESULTS")
    print(f"{'═'*70}")
    for r in results:
        print(f"  {r['question']:<12} Eng: {r.get('english_ratio',0)*100:>3.0f}%  TPS: {r.get('tps',0):>5.1f}")
